config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :list, uniqueness: { scope: :movie }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]
  def index
    @lists = List.all
  end

  def show
    @bookmarks = Bookmark.where("list_id = '#{params[:id]}'")
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a movie to <%=@list.name %></h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie_id, :collection => @movies %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Back to list", lists_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar-lewagon d-flex align-items-center border border-dark">
  <h1 class="m-3">All lists</h1>
  <%= link_to "Add a list", new_list_path, class: "btn btn-primary m-3"%>
</div>
<ul class="p-3 m-3 cards">
  <% @lists.each do |list| %>
    <%= link_to list_path(list), class:"link" do%>
      <li class="card-list p-3 m-3 d-flex justify-content-center align-items-center"
          style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>')">
        <h2><%=list.name%></h2>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>Add a list</h1>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>
<%= link_to "Back to list", lists_path%>

app/views/lists/show.html.erb
<div class="navbar-lewagon d-flex align-items-center border border-dark">
  <h1 class="m-3"><%= @list.name %></h1>
  <%= link_to "Add a list", new_list_path, class: "btn btn-primary m-3"%>
</div>

<ul class="cards-movies">
  <% @bookmarks.each do |bookmark| %>
    <li>
      <div class="card-movie d-flex flex-column m-3 align-items-center justify-content-between"
          style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=bookmark.movie.poster_url%>)">
        <div class="d-flex flex-row align-items-top justify-content-between">
          <div>
            <h2><%=bookmark.movie.title%></h2>
            <p><%=bookmark.movie.overview%></p>
          </div>
          <div>
            <%= link_to "Delete",
              bookmark_path(bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "btn btn-danger"
            %>
          </div>
        </div>
        <div>
          <p><%= bookmark.comment%></p>
          <p>Rating: <%= bookmark.movie.rating%></p>
        </div>
      </div>
</li>
  <% end %>
</ul>
<%= link_to "Add a movie", new_list_bookmark_path(@list), class: "btn btn-success"%>
<%= link_to "Back to list", lists_path, class: "btn btn-light"%>